WebProject_eBiletApp/eBiletApp/eBiletApp/Models/Film.cs
using eBiletApp.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace eBiletApp.Models
{
    public class Film
    {
        public int FilmId { get; set; }

        [Display(Name = "Film Adı")]
        public string FilmAdi { get; set; }

        [Display(Name = "Film Hakkında")]
        [StringLength(10000,MinimumLength =100,ErrorMessage ="Film Açıklaması 100-10000 karakter arasında olmalıdır")]
        public string FilmHakkinda { get; set; }

        [Display(Name ="Film Seans Saatleri")]
        public string FilmBaslamaSaati1 { get; set; }
        public string FilmBaslamaSaati2 { get; set; }
        public string FilmBaslamaSaati3 { get; set; }

        [Display(Name = "Film Fotoğrafı")]
        public string FilmFotografi { get; set; }

        [Display(Name = "Film Türü")]
        public FilmKategorisi FilmKategorisi { get; set; }

        [Display(Name = "Film Ücreti")]
        public float FilmUcreti { get; set; }

        [Display(Name = "Film Oyuncuları")]
        public ICollection<FilmOyuncu> FilmlerOyuncular { get; set; }

        public int SinemaId { get; set; }
        [ForeignKey("SinemaId")]
        [Display(Name = "Sinema Adı")]
        public Sinema Sinema { get; set; }

        public int YonetmenId { get; set; }

        [Display(Name = "Yönetmen Adı")]
        [ForeignKey("YonetmenId")]
        public Yonetmen Yonetmen { get; set; }
    }
    
}

WebProject_eBiletApp/eBiletApp/eBiletApp/Controllers/OyuncuController.cs
using eBiletApp.Data;
using eBiletApp.Data.Repositories.Abstract;
using eBiletApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace eBiletApp.Controllers
{
    [Authorize(Roles = Roller.Admin)]
    public class OyuncuController : Controller
    {

        private readonly IOyuncuRepository _repo;

        public OyuncuController(IOyuncuRepository repo)
        {
            _repo = repo;
        }
        [AllowAnonymous]
        public async  Task<IActionResult> Index()
        {
            var oyuncular = await _repo.ListAll();
            return View(oyuncular);
        }

        [HttpPost]
        public  IActionResult Create(IFormFile file,[Bind("OyuncuId,OyuncuFotografi,OyuncuAdSoyad,OyuncuHakkinda")] Oyuncu o)
        { 
            //Oyuncu resmini upload etmek için
            if (file!=null&&file.Length > 0)
            {
                    string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                    string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Oyuncular"));
                    using(var fileStream=new FileStream(Path.Combine(path,dosyaAdi),FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    o.OyuncuFotografi = "~/images/Oyuncular/"+ dosyaAdi;
            }

            if (ModelState.IsValid)
            {     
               
                
                    _repo.Add(o);
                    return RedirectToAction(nameof(Index));
                
            }

            return View(o);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {

            var oyuncu =  _repo.GetById(id);
                
            if (oyuncu == null)
            {
                return NotFound();
            }

            return View(oyuncu);
        }

        public  IActionResult Edit(int id)
        {

            var oyuncu = _repo.GetById(id);
            if (oyuncu == null)
            {
                return NotFound();
            }
            return View(oyuncu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("OyuncuId,OyuncuFotografi,OyuncuAdSoyad,OyuncuHakkinda")] Oyuncu o, IFormFile file)
        {
            //Oyuncu resmini upload etmek için
            if (file != null && file.Length > 0)
            {
                string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Oyuncular"));
                using (var fileStream = new FileStream(Path.Combine(path, dosyaAdi), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                o.OyuncuFotografi = "~/images/Oyuncular/" + dosyaAdi;
            }

            if (id != o.OyuncuId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {               
                _repo.Update(id, o);
                
                return RedirectToAction(nameof(Index));
            }
            return View(o);
        }


        
        public IActionResult Delete(int id)
        {

            var oyuncu = _repo.GetById(id);
            if (oyuncu == null)
            {
                return NotFound();
            }

            return View(oyuncu);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public  IActionResult DeleteConfirmed(int id)
        {
            var oyuncu = _repo.GetById(id);
            _repo.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebProject_eBiletApp/eBiletApp/eBiletApp/Controllers/SinemaController.cs
using eBiletApp.Data;
using eBiletApp.Data.Repositories.Abstract;
using eBiletApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace eBiletApp.Controllers
{
    [Authorize(Roles = Roller.Admin)]
    public class SinemaController : Controller
    {
        private readonly ISinemaRepository _repo;
        public SinemaController(ISinemaRepository repo)
        {
            _repo = repo;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var sinemalar = await _repo.ListAll();
            return View(sinemalar);
        }


        [HttpPost]
        public IActionResult Create(IFormFile file, [Bind("SinemaId,SinemaFotografi,SinemaAdi,SinemaHakkinda")] Sinema s)
        {
            //Sinema resmini upload etmek için
            if (file != null && file.Length > 0)
            {
                string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Sinemalar"));
                using (var fileStream = new FileStream(Path.Combine(path, dosyaAdi), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                s.SinemaFotografi = "~/images/Sinemalar/" + dosyaAdi;
            }

            if (ModelState.IsValid)
            {


                _repo.Add(s);
                return RedirectToAction(nameof(Index));

            }

            return View(s);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {

            var sinema = _repo.GetById(id);

            if (sinema == null)
            {
                return NotFound();
            }

            return View(sinema);
        }


        public IActionResult Edit(int id)
        {

            var sinema = _repo.GetById(id);
            if (sinema == null)
            {
                return NotFound();
            }
            return View(sinema);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("SinemaId,SinemaFotografi,SinemaAdi,SinemaHakkinda")] Sinema s, IFormFile file)
        {
            //Sinema resmini upload etmek için
            if (file != null && file.Length > 0)
            {
                string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Sinemalar"));
                using (var fileStream = new FileStream(Path.Combine(path, dosyaAdi), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                s.SinemaFotografi = "~/images/Sinemalar/" + dosyaAdi;
            }

            if (id != s.SinemaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _repo.Update(id, s);

                return RedirectToAction(nameof(Index));
            }
            return View(s);
        }


        public IActionResult Delete(int id)
        {

            var sinema = _repo.GetById(id);
            if (sinema == null)
            {
                return NotFound();
            }

            return View(sinema);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var sinema = _repo.GetById(id);
            _repo.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebProject_eBiletApp/eBiletApp/eBiletApp/Controllers/SiparisController.cs
using eBiletApp.Data;
using eBiletApp.Data.Repositories;
using eBiletApp.Data.Repositories.Abstract;
using eBiletApp.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eBiletApp.Controllers
{
    [Authorize]
    public class SiparisController : Controller
    {
        private readonly ISiparisRepository _siparisRepo;
        private readonly SepetRepository _sepetRepo;
        private readonly IFilmRepository _filmRepo;

        public SiparisController(ISiparisRepository siparisRepo,SepetRepository sepetRepo, IFilmRepository filmRepo)
        {
            _siparisRepo = siparisRepo;
            _sepetRepo = sepetRepo;
            _filmRepo = filmRepo;
        }


        public IActionResult Index()
        {
            //Alışveriş Sepeti Actionı
            var sepettekiler = _sepetRepo.SepeteEklenenler();
            _sepetRepo.Sepettekiler = sepettekiler;

            var svm = new SepetVM();
            svm.SepetRepo = _sepetRepo;
            svm.ToplamTutar = _sepetRepo.SepetToplamTutar();

            return View(svm);
        }

        public async Task< IActionResult> TumSiparisler()
        {
            //claim based, role based'ten farklı olarak talep bazlı bir yöntemdir.
            string kullaniciId = User.FindFirstValue(ClaimTypes.NameIdentifier); //claim type nameidentifier ile id bulunabilir
            string rol = User.FindFirstValue(ClaimTypes.Role);
            var siparisler = await _siparisRepo.SiparisleriGetir(kullaniciId,rol);
            return View(siparisler);
        }

        public RedirectToActionResult SepeteEkleArtir(int id)
        {
            var film = _filmRepo.FilmGetir(id);
            if (film != null)
            {               
                _sepetRepo.SepeteEkle(film);
            }
            return RedirectToAction(nameof(Index));
        }

        public RedirectToActionResult SepettenCikarAzalt(int id)
        {
            var film = _filmRepo.FilmGetir(id);
            if (film != null)
            {
                _sepetRepo.SepettenCikar(film);
            }
            return RedirectToAction(nameof(Index));
        }

       public async Task<IActionResult> SiparisiTamamla()
        {
            var urunler = _sepetRepo.SepeteEklenenler();
            //claim based, role based'ten farklı olarak talep bazlı bir yöntemdir.
            string kullaniciId = User.FindFirstValue(ClaimTypes.NameIdentifier); //claim type nameidentifier ile id bulunabilir
            string kullaniciEmail = User.FindFirstValue(ClaimTypes.Email);

           await _siparisRepo.SiparisiKaydet(urunler, kullaniciId, kullaniciEmail);
           await _sepetRepo.SepetiBosalt();
            return View("SiparisTamamlandi");
        }
    }
}

WebProject_eBiletApp/eBiletApp/eBiletApp/Controllers/YonetmenController.cs
using eBiletApp.Data;
using eBiletApp.Data.Repositories.Abstract;
using eBiletApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace eBiletApp.Controllers
{
    [Authorize(Roles = Roller.Admin)]
    public class YonetmenController : Controller
    {
        private readonly IYonetmenRepository _repo;

        public YonetmenController(IYonetmenRepository repo)
        {
            _repo = repo;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var yonetmenler = await _repo.ListAll(); ;
            return View(yonetmenler);

        }

        [HttpPost]
        public IActionResult Create(IFormFile file, [Bind("YonetmenId,YonetmenFotografi,YonetmenAdSoyad,YonetmenHakkinda")] Yonetmen y)
        {
            //Yonetmen resmini upload etmek için
            if (file != null && file.Length > 0)
            {
                string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Yonetmenler"));
                using (var fileStream = new FileStream(Path.Combine(path, dosyaAdi), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                y.YonetmenFotografi = "~/images/Yonetmenler/" + dosyaAdi;
            }

            if (ModelState.IsValid)
            {


                _repo.Add(y);
                return RedirectToAction(nameof(Index));

            }

            return View(y);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {

            var yonetmen = _repo.GetById(id);

            if (yonetmen == null)
            {
                return NotFound();
            }

            return View(yonetmen);
        }

        public IActionResult Edit(int id)
        {

            var yonetmen = _repo.GetById(id);
            if (yonetmen == null)
            {
                return NotFound();
            }
            return View(yonetmen);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("YonetmenId,YonetmenFotografi,YonetmenAdSoyad,YonetmenHakkinda")] Yonetmen y, IFormFile file)
        {
            //Yonetmen resmini upload etmek için
            if (file != null && file.Length > 0)
            {
                string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Yonetmenler"));
                using (var fileStream = new FileStream(Path.Combine(path, dosyaAdi), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
               y.YonetmenFotografi = "~/images/Yonetmenler/" + dosyaAdi;
            }

            if (id != y.YonetmenId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _repo.Update(id, y);

                return RedirectToAction(nameof(Index));
            }
            return View(y);
        }

        public IActionResult Delete(int id)
        {

            var yonetmen = _repo.GetById(id);
            if (yonetmen == null)
            {
                return NotFound();
            }

            return View(yonetmen);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var yonetmen = _repo.GetById(id);
            _repo.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }

}

WebProject_eBiletApp/eBiletApp/eBiletApp/Views/Film/Delete.cshtml
@model eBiletApp.Models.Film
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = "Film Sil";
}

<h3>@localizer["Silmek istediğinize emin misiniz?"]</h3>
<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmAdi)
        </dt>
        <dd class="col-sm-10 font-weight-bold ">
            @Html.DisplayFor(model => model.FilmAdi)
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmFotografi)
        </dt>
        <dd class="col-sm-10">
            <img style="width:200px; height:250px;" src="@Model.FilmFotografi" asp-append-version="true">
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmHakkinda)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FilmHakkinda)
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmBaslamaSaati1)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FilmBaslamaSaati1)
            @Html.DisplayFor(model => model.FilmBaslamaSaati2)
            @Html.DisplayFor(model => model.FilmBaslamaSaati3)
        </dd>

        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmKategorisi)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FilmKategorisi)
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmUcreti)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FilmUcreti) TL
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.Sinema)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Sinema" asp-action="Details" asp-route-id="@Model.Sinema.SinemaId">
                @Model.Sinema.SinemaAdi
            </a>
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.Yonetmen)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Yonetmen" asp-action="Details" asp-route-id="@Model.Yonetmen.YonetmenId">
                @Model.Yonetmen.YonetmenAdSoyad
            </a>
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmlerOyuncular)
        </dt>
        <dd class="row col-sm-10">
            @foreach (var item in Model.FilmlerOyuncular)
            {
                <div class="column mr-5">
                    <img style="width:100px; height:150px;" src="@item.Oyuncu.OyuncuFotografi" asp-append-version="true">
                    <br />
                    <a asp-controller="Oyuncu" asp-action="Details" asp-route-id="@item.Oyuncu.OyuncuId">
                        @item.Oyuncu.OyuncuAdSoyad
                    </a>
                </div>
            }

        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="FilmId" />
        <input type="submit" value="@localizer["Sil"]" class="btn btn-danger" />
        <a class="btn btn-secondary float-right" asp-action="Index">@localizer["Geri Dön"]</a>
    </form>
</div>

WebProject_eBiletApp/eBiletApp/eBiletApp/Views/Film/Details.cshtml
@model eBiletApp.Models.Film
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = "Details";
}


<div>
    <h4>@localizer["Film Bilgileri"]</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmAdi)
        </dt>
        <dd class="col-sm-10 font-weight-bold ">
            @Html.DisplayFor(model => model.FilmAdi)
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmFotografi)
        </dt>
        <dd class="col-sm-10">
            <img style="width:200px; height:250px;" src="@Model.FilmFotografi" asp-append-version="true">
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmHakkinda)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FilmHakkinda)
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmBaslamaSaati1)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FilmBaslamaSaati1)
            @Html.DisplayFor(model => model.FilmBaslamaSaati2)
            @Html.DisplayFor(model => model.FilmBaslamaSaati3)
        </dd>

        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmKategorisi)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FilmKategorisi)
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmUcreti)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FilmUcreti) TL
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.Sinema)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Sinema" asp-action="Details" asp-route-id="@Model.Sinema.SinemaId">
                @Model.Sinema.SinemaAdi
            </a>
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.Yonetmen)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Yonetmen" asp-action="Details" asp-route-id="@Model.Yonetmen.YonetmenId">
                @Model.Yonetmen.YonetmenAdSoyad
            </a>
        </dd>
        <dt class="col-sm-2 pb-5 align-self-center">
            @Html.DisplayNameFor(model => model.FilmlerOyuncular)
        </dt>
        <dd class="row col-sm-10">
            @foreach (var item in Model.FilmlerOyuncular)
            {
                <div class="column mr-5">
                    <img style="width:100px; height:150px;" src="@item.Oyuncu.OyuncuFotografi" asp-append-version="true">
                    <br />
                    <a asp-controller="Oyuncu" asp-action="Details" asp-route-id="@item.Oyuncu.OyuncuId">
                        @item.Oyuncu.OyuncuAdSoyad
                    </a>
                </div>
            }

        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Siparis" asp-action="SepeteEkleArtir" asp-route-id="@Model.FilmId" class="btn btn-dark text-white">
        @localizer["Bilet Al"]  @Model.FilmUcreti TL
    </a>
    <a class="btn btn-secondary ml-3" asp-action="Index">@localizer["Geri Dön"]</a>
</div>

WebProject_eBiletApp/eBiletApp/eBiletApp/Views/Film/Index.cshtml
@model IEnumerable<eBiletApp.Models.Film>
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@{
    ViewData["Title"] = "Filmler";
}

<div class="row" style="align-items:stretch">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 600px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class=" btn btn-dark text-white float-md-right" style="font-size:large" asp-action="Edit" asp-route-id="@item.FilmId">@localizer["Düzenle"]</a>
                                    }
                                    <a class="text-center">            @item.FilmAdi   </a>
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="btn btn-danger text-white float-md-right" style="font-size:large" asp-action="Delete" asp-route-id="@item.FilmId">@localizer["Sil"]</a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text"><b>@localizer["Film Hakkında"]: </b>@item.FilmHakkinda.Substring(0,100)...</p>
                            <p class="card-text"><b>@localizer["Kategori"]:  </b>@item.FilmKategorisi</p>
                            <p class="card-text"><b>@localizer["Sinema"]:  </b>@item.Sinema.SinemaAdi</p>
                            <p class="card-text" >
                                <b>@localizer["Seans Seçiniz"]: </b>
                                <select name="saat" id="saat" style=" border: none; overflow: hidden; background-color: whitesmoke;">
                                    <option class="btn btn-dark card-text" value="bir">@item.FilmBaslamaSaati1</option>
                                    <option class="btn btn-dark card-text" value="iki">@item.FilmBaslamaSaati2</option>
                                    <option class="btn btn-dark card-text" value="uc">@item.FilmBaslamaSaati3</option>
                                </select>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.FilmFotografi" width="100%" height="380px"  asp-append-version="true" >
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer">
                            <p class="card-text">
                                <a class="btn btn-outline-secondary float-right" asp-action="Details" asp-route-id="@item.FilmId">
                                    @localizer["Daha Fazla"]
                                </a>
                                <a asp-controller="Siparis" asp-action="SepeteEkleArtir" asp-route-id="@item.FilmId" class="btn btn-success text-white">
                                    @localizer["Bilet Al"] @item.FilmUcreti TL
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>