WebProject_eBiletApp/eBiletApp/eBiletApp/Controllers/FilmController.cs
using eBiletApp.Data;
using eBiletApp.Data.Repositories.Abstract;
using eBiletApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace eBiletApp.Controllers
{
    [Authorize(Roles =Roller.Admin)]
    public class FilmController : Controller
    {
        private readonly IFilmRepository _repo;
        public FilmController(IFilmRepository repo)
        {
            _repo = repo;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var filmler = await _repo.ListAll(m => m.Sinema);
            return View(filmler);
        }
        [AllowAnonymous]
        public IActionResult Details(int id)
        {

            var film = _repo.FilmGetir(id);

            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {

            //film eklenirken seçilmesi gereken sinema,oyuncu,yönetmen listeleri
            var filmVerileri = await _repo.FilmVerileri();
            ViewData["SinemaId"] = new SelectList(filmVerileri.Sinemalar, "SinemaId", "SinemaAdi");
            ViewData["OyuncuId"] = new SelectList(filmVerileri.Oyuncular, "OyuncuId", "OyuncuAdSoyad");
            ViewData["YonetmenId"] = new SelectList(filmVerileri.Yonetmenler, "YonetmenId", "YonetmenAdSoyad");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile file, FilmVM film)
        {
            var filmVerileri = await _repo.FilmVerileri();
            ViewData["SinemaId"] = new SelectList(filmVerileri.Sinemalar, "SinemaId", "SinemaAdi");
            ViewData["OyuncuId"] = new SelectList(filmVerileri.Oyuncular, "OyuncuId", "OyuncuAdSoyad");
            ViewData["YonetmenId"] = new SelectList(filmVerileri.Yonetmenler, "YonetmenId", "YonetmenAdSoyad");


            if (file != null && file.Length > 0)
            {
                string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Filmler"));
                using (var fileStream = new FileStream(Path.Combine(path, dosyaAdi), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
               film.FilmFotografi = "~/images/Filmler/" + dosyaAdi;
            }

            if (ModelState.IsValid)
            {

                await _repo.FilmEkle(film);

                return RedirectToAction(nameof(Index));
            }
            
            return View(film);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            var film =  _repo.FilmGetir(id);

            var filmSon = new FilmVM();
            filmSon.FilmId = film.FilmId;
            filmSon.FilmAdi = film.FilmAdi;
            filmSon.FilmBaslamaSaati1 = film.FilmBaslamaSaati1;
            filmSon.FilmBaslamaSaati2 = film.FilmBaslamaSaati2;
            filmSon.FilmBaslamaSaati3 = film.FilmBaslamaSaati3;
            filmSon.FilmFotografi = film.FilmFotografi;
            filmSon.FilmHakkinda = film.FilmHakkinda;
            filmSon.FilmKategorisi = film.FilmKategorisi;
            filmSon.FilmUcreti = film.FilmUcreti;
            filmSon.OyuncuListesi = film.FilmlerOyuncular.Select(m => m.OyuncuId).ToList();
            filmSon.SinemaId = film.SinemaId;
            filmSon.YonetmenId = film.YonetmenId;


            var filmVerileri = await _repo.FilmVerileri();
            ViewData["SinemaId"] = new SelectList(filmVerileri.Sinemalar, "SinemaId", "SinemaAdi");
            ViewData["OyuncuId"] = new SelectList(filmVerileri.Oyuncular, "OyuncuId", "OyuncuAdSoyad");
            ViewData["YonetmenId"] = new SelectList(filmVerileri.Yonetmenler, "YonetmenId", "YonetmenAdSoyad");
            return View(filmSon);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormFile file, FilmVM film, int id)
        {
            var filmVerileri = await _repo.FilmVerileri();
            ViewData["SinemaId"] = new SelectList(filmVerileri.Sinemalar, "SinemaId", "SinemaAdi");
            ViewData["OyuncuId"] = new SelectList(filmVerileri.Oyuncular, "OyuncuId", "OyuncuAdSoyad");
            ViewData["YonetmenId"] = new SelectList(filmVerileri.Yonetmenler, "YonetmenId", "YonetmenAdSoyad");


            if (file != null && file.Length > 0)
            {
                string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Filmler"));
                using (var fileStream = new FileStream(Path.Combine(path, dosyaAdi), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                film.FilmFotografi = "~/images/Filmler/" + dosyaAdi;
            }

            if (ModelState.IsValid)
            {

                await _repo.FilmGuncelle(film);

                return RedirectToAction(nameof(Index));
            }

            return View(film);
        }

        public IActionResult Delete(int id)
        {
            var film = _repo.FilmGetir(id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);

        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var film = _repo.GetById(id);
            _repo.Delete(id); //id'ye göre bulunan filmi, filmrepository'deki delete metodunun içindeki remove'a vererek silme işlemi gerçekleştirir. 
            return RedirectToAction(nameof(Index));

        }

        [AllowAnonymous]
        public async Task<IActionResult> AramaSonucu(string arananFilm)
        {
            var filmler = await  _repo.ListAll(m => m.Sinema);
            if (string.IsNullOrEmpty(arananFilm) == true) 
                return View("Index", filmler);


             var sonuc = filmler.Where(m => m.FilmAdi.Contains(arananFilm)).ToList();
            return View("Index", sonuc);
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult MultiLang(string culture,string url)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.Now.AddDays(30) });
            return LocalRedirect(url);
        }

    }
}

WebProject_eBiletApp/eBiletApp/eBiletApp/Controllers/OyuncuController.cs
using eBiletApp.Data;
using eBiletApp.Data.Repositories.Abstract;
using eBiletApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace eBiletApp.Controllers
{
    [Authorize(Roles = Roller.Admin)]
    public class OyuncuController : Controller
    {

        private readonly IOyuncuRepository _repo;

        public OyuncuController(IOyuncuRepository repo)
        {
            _repo = repo;
        }
        [AllowAnonymous]
        public async  Task<IActionResult> Index()
        {
            var oyuncular = await _repo.ListAll();
            return View(oyuncular);
        }

        [HttpPost]
        public  IActionResult Create(IFormFile file,[Bind("OyuncuId,OyuncuFotografi,OyuncuAdSoyad,OyuncuHakkinda")] Oyuncu o)
        { 
            //Oyuncu resmini upload etmek için
            if (file!=null&&file.Length > 0)
            {
                    string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                    string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Oyuncular"));
                    using(var fileStream=new FileStream(Path.Combine(path,dosyaAdi),FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    o.OyuncuFotografi = "~/images/Oyuncular/"+ dosyaAdi;
            }

            if (ModelState.IsValid)
            {     
               
                
                    _repo.Add(o);
                    return RedirectToAction(nameof(Index));
                
            }

            return View(o);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {

            var oyuncu =  _repo.GetById(id);
                
            if (oyuncu == null)
            {
                return NotFound();
            }

            return View(oyuncu);
        }

        public  IActionResult Edit(int id)
        {

            var oyuncu = _repo.GetById(id);
            if (oyuncu == null)
            {
                return NotFound();
            }
            return View(oyuncu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("OyuncuId,OyuncuFotografi,OyuncuAdSoyad,OyuncuHakkinda")] Oyuncu o, IFormFile file)
        {
            //Oyuncu resmini upload etmek için
            if (file != null && file.Length > 0)
            {
                string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Oyuncular"));
                using (var fileStream = new FileStream(Path.Combine(path, dosyaAdi), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                o.OyuncuFotografi = "~/images/Oyuncular/" + dosyaAdi;
            }

            if (id != o.OyuncuId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {               
                _repo.Update(id, o);
                
                return RedirectToAction(nameof(Index));
            }
            return View(o);
        }


        
        public IActionResult Delete(int id)
        {

            var oyuncu = _repo.GetById(id);
            if (oyuncu == null)
            {
                return NotFound();
            }

            return View(oyuncu);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public  IActionResult DeleteConfirmed(int id)
        {
            var oyuncu = _repo.GetById(id);
            _repo.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebProject_eBiletApp/eBiletApp/eBiletApp/Controllers/SinemaController.cs
using eBiletApp.Data;
using eBiletApp.Data.Repositories.Abstract;
using eBiletApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace eBiletApp.Controllers
{
    [Authorize(Roles = Roller.Admin)]
    public class SinemaController : Controller
    {
        private readonly ISinemaRepository _repo;
        public SinemaController(ISinemaRepository repo)
        {
            _repo = repo;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var sinemalar = await _repo.ListAll();
            return View(sinemalar);
        }


        [HttpPost]
        public IActionResult Create(IFormFile file, [Bind("SinemaId,SinemaFotografi,SinemaAdi,SinemaHakkinda")] Sinema s)
        {
            //Sinema resmini upload etmek için
            if (file != null && file.Length > 0)
            {
                string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Sinemalar"));
                using (var fileStream = new FileStream(Path.Combine(path, dosyaAdi), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                s.SinemaFotografi = "~/images/Sinemalar/" + dosyaAdi;
            }

            if (ModelState.IsValid)
            {


                _repo.Add(s);
                return RedirectToAction(nameof(Index));

            }

            return View(s);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Details(int id)
        {

            var sinema = _repo.GetById(id);

            if (sinema == null)
            {
                return NotFound();
            }

            return View(sinema);
        }


        public IActionResult Edit(int id)
        {

            var sinema = _repo.GetById(id);
            if (sinema == null)
            {
                return NotFound();
            }
            return View(sinema);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("SinemaId,SinemaFotografi,SinemaAdi,SinemaHakkinda")] Sinema s, IFormFile file)
        {
            //Sinema resmini upload etmek için
            if (file != null && file.Length > 0)
            {
                string dosyaAdi = Guid.NewGuid() + Path.GetExtension(file.FileName);
                string path = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Sinemalar"));
                using (var fileStream = new FileStream(Path.Combine(path, dosyaAdi), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                s.SinemaFotografi = "~/images/Sinemalar/" + dosyaAdi;
            }

            if (id != s.SinemaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _repo.Update(id, s);

                return RedirectToAction(nameof(Index));
            }
            return View(s);
        }


        public IActionResult Delete(int id)
        {

            var sinema = _repo.GetById(id);
            if (sinema == null)
            {
                return NotFound();
            }

            return View(sinema);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var sinema = _repo.GetById(id);
            _repo.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebProject_eBiletApp/eBiletApp/eBiletApp/Views/Shared/_Culture.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> locOptions


@{
    var Culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    
    
    //dropdownda listeleme yapmak icin
    var DilListe = locOptions.Value.SupportedUICultures.Select(m => new SelectListItem { Value = m.Name, Text = m.Name }).ToList();
    var url = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<div>
    <form asp-action="MultiLang" asp-controller="Film" method="post" asp-route-url="@url">
        <select class="nav-item rounded" name="culture" asp-for="@Culture.RequestCulture.UICulture.Name" asp-items="DilListe" onchange="this.form.submit();">
        </select>
    </form>
</div>

WebProject_eBiletApp/eBiletApp/eBiletApp/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Identity.UserManager<Kullanici> kullanici
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eBilet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>

<body style="background: linear-gradient(45deg,  ghostwhite, lightblue);">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark border-bottom box-shadow mb-3" style="background: linear-gradient(45deg, lightblue, ghostwhite); ">
            <div class="float-md-right"><partial name="_Culture" /></div>
            <div class="container-fluid">

                <a class="navbar-brand" asp-controller="Film" asp-action="Index"><h1 class="text-dark" >eBilet</h1>
                <img src="~/images/Logo.png" style="width: 30px; height: 30px; display: inline-block;" />
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <form class="form-inline" asp-controller="Film" asp-action="AramaSonucu">
                    <input type="search" name="arananFilm" class="form-control rounded " placeholder="@localizer["Film Ara"]" aria-label="Search"
                           aria-describedby="search-addon" />

                    <button type="submit" class="btn btn-light" style="margin-left:3px;">@localizer["Ara"]</button>
                </form>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1 flex-sm-row-reverse">

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <button class="btn btn-outline-light dropdown-toggle border-dark text-dark" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin Menu
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-controller="Oyuncu" asp-action="Index">@localizer["Oyuncular"]</a>
                                    <a class="dropdown-item" asp-controller="Yonetmen" asp-action="Index">@localizer["Yönetmenler"]</a>
                                    <a class="dropdown-item" asp-controller="Sinema" asp-action="Index">@localizer["Sinemalar"]</a>
                                    <a class="dropdown-item" asp-controller="Film" asp-action="Create">@localizer["Film Ekle"]</a>
                                </div>

                            </li>
                        }




                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item rounded dropdown" style="margin-left: 20px;">
                                <button class="btn btn-outline-light border-dark dropdown-toggle text-dark mr-5" type="button" id="kullanici" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @localizer["Hoşgeldiniz,"] @kullanici.GetUserName(User)
                                </button>
                                <div class="dropdown-menu" aria-labelledby="kullanici">
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {<a class="dropdown-item text-center" asp-controller="Account" asp-action="TumKullanicilar">@localizer["Kullanıcılar"]</a>}
                                    <a class="dropdown-item text-center" asp-controller="Siparis" asp-action="TumSiparisler">@localizer["Siparişler"]</a>
                                    <form asp-controller="Account" asp-action="Cikis">
                                        <button class="dropdown-item" style="background:none;border:none; text-align:center;">@localizer["Çıkış"]</button>
                                    </form>
                                </div>
                            </li>

                            <li class="nav-item rounded" style="margin-left: 20px; ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Siparis" asp-action="Index">
                                    @localizer["Sepetim"]
                                    <img src="~/images/shopping-cart.png" style="width: 30px; height: 30px; display: inline-block;" />
                                </a>
                            </li>
                        }

                        else
                        {
                            <li class="nav-item rounded" style=" margin-left: 20px; ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Uyelik">
                                    @localizer["Üye Ol"]
                                    <img src="~/images/sign-up.png" style="width: 30px; height: 30px; display: inline-block;" />
                                </a>
                            </li>
                            <li class="nav-item rounded" style="margin-left: 20px; ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">
                                    @localizer["Giriş Yap"]
                                    <img src="~/images/login.png" style="width: 30px; height: 30px; display: inline-block;" />
                                </a>
                            </li>
                        }

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="footer  font-small pt-4 " style="background: linear-gradient(45deg, lightblue, ghostwhite);">
        <div class="container-fluid text-center text-md-left text-dark" style="white-space: normal;">
            <div class="row">
                <div class="col-md-5 mt-md-0 mt-3">
                    <h5 class="font-weight-bold text-dark">@localizer["Takip"]</h5>
                    <p>INSTAGRAM</p>
                    <p>FACEBOOK</p>
                    <p>YOUTUBE</p>
                </div>

                <div class="col-md-4 mb-md-0 mb-3 ">

                    <h5 class=" text-dark font-weight-bold ">@localizer["Kategoriler"]</h5>

                    <ul class="list-unstyled ">
                        <li>
                            <a class="text-dark" href="#!">@localizer["Komedi"]</a>
                        </li>
                        <li>
                            <a class="text-dark" href="#!">@localizer["Dram"]</a>
                        </li>
                        <li>
                            <a class="text-dark" href="#!">@localizer["Aksiyon"]</a>
                        </li>
                    </ul>

                </div>

                <div class="col-md-3 mb-md-0 mb-3">

                    <h5 class=" text-dark font-weight-bold">@localizer["Biz Kimiz?"]</h5>

                    <ul class="list-unstyled">
                        <li>
                            <a class="text-dark" href="#!">@localizer["Hakkımızda"]</a>
                        </li>
                        <li>
                            <a class="text-dark" href="#!">@localizer["İletişim"]</a>
                        </li>
                        <li>
                            <a class="text-dark" href="#!">@localizer["Sık Sorulan"]</a>
                        </li>
                    </ul>

                </div>

            </div>

        </div>

        <div class="footer-copyright text-center text-dark py-3">
            <h5 class="text-dark ">&copy; 2022 - eBilet</h5>
        </div>

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>